name: Build and deploy from main and create a new release
on:
    push:
        branches:
            - 'main'

jobs:
    build:
        name: Build image
        permissions:
            contents: read
            id-token: write
        uses: ./.github/workflows/build-image.yml
        secrets:
            NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

    deploy-dev:
        name: Deploy to dev
        permissions:
            contents: read
            id-token: write
        uses: ./.github/workflows/deploy-to-nais.yml
        needs: build
        with:
            image: ${{ needs.build.outputs.image }}
            cluster: dev-gcp

    deploy-prod-gcp:
        name: Deploy to prod-gcp
        permissions:
            contents: read
            id-token: write
        uses: ./.github/workflows/deploy-to-nais.yml
        needs: build
        with:
            image: ${{ needs.build.outputs.image }}
            cluster: prod-gcp

    release:
        name: Create a new release
        needs: deploy-prod-gcp
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - name: Generate unique tag name
              run: echo "TAG_NAME=$(date +%s)" >> $GITHUB_ENV
            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  target_commitish: main
                  tag_name: release/prod@${{ env.TAG_NAME }} # Generates a unique tag using timestamp
                  name: Release ${{ github.ref_name }}
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # This is a PAT with repo permissions